// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZGQ8YHD2VpICtR7A-afcFxY-r3voyAkE',
    appId: '1:132559657246:web:5dfafa575982f97eadd10f',
    messagingSenderId: '132559657246',
    projectId: 'habittracker-83c82',
    authDomain: 'habittracker-83c82.firebaseapp.com',
    storageBucket: 'habittracker-83c82.firebasestorage.app',
    measurementId: 'G-X9L5W8BKV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvePdZoDrkvPioCNpg3vp67ppJ0M-U-iE',
    appId: '1:132559657246:android:0a2683d19b87c57fadd10f',
    messagingSenderId: '132559657246',
    projectId: 'habittracker-83c82',
    storageBucket: 'habittracker-83c82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHNedXLEqhlSo7MAbzopreTCn0ALqg9Tw',
    appId: '1:132559657246:ios:dbec8a20013e45f9add10f',
    messagingSenderId: '132559657246',
    projectId: 'habittracker-83c82',
    storageBucket: 'habittracker-83c82.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHNedXLEqhlSo7MAbzopreTCn0ALqg9Tw',
    appId: '1:132559657246:ios:dbec8a20013e45f9add10f',
    messagingSenderId: '132559657246',
    projectId: 'habittracker-83c82',
    storageBucket: 'habittracker-83c82.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZGQ8YHD2VpICtR7A-afcFxY-r3voyAkE',
    appId: '1:132559657246:web:8b7ead9c52c7f4ecadd10f',
    messagingSenderId: '132559657246',
    projectId: 'habittracker-83c82',
    authDomain: 'habittracker-83c82.firebaseapp.com',
    storageBucket: 'habittracker-83c82.firebasestorage.app',
    measurementId: 'G-PWB68SR4PC',
  );
}
